### PR TITLE
Add Troubleshooting for ESP32-C3 based devices; Fixes #57

### LINKED ISSUE #57: SwitchBot TH crashing esp32 c3 - switchbot_plugmini_W1901400
ref #47 
I am using the blerry dev branch and the development branch of Tasmota on these: https://templates.blakadder.com/switchbot_plugmini_W1901400.html

ATCpvvx alone seems to work fine on one plug and not cause issues but on another with just one WoSensorTH it will last up to an hour before freezing and becoming completely unresponsive. The button on the side to toggle the plug relay is dead and no http or anything. Pulling the plug out of the outlet and replugging it is the only way to bring it back... It then runs for a random time not more than an hour and repeat.

I am starting to suspect exclusively WoSensorTH as I've had others with ATCpvvx and WP6003 with no issue.

What else can I provide to help troubleshoot? turn on berry debug? send to syslog?

### PR DESCRIPTION
**Pull request by edestecd**
Add some Doc about ESP32-C3

### CODE REVIEW

**Comment by digiblur** [comment]
Not sure I would call them limitations. The C3 has been stable the most for me.

Using the plug and bulb with the correct template and bin https://digiblur.com/wiki/devices/bulbs/switchbot_e26_w1401400

**Comment by edestecd** [comment]
I can change whatever you like. I'm just trying to help someone else avoid my experience the last few weeks

**Comment by edestecd** [comment]
I'm using exactly that template etc. I do make my own tasmota builds but I'm mainly just putting in my wifi/mqtt settings

**Comment by digiblur** [comment]
https://us.switch-bot.com/collections/all/products/switchbot-plug-mini

**Comment by edestecd** [comment]
done

**Pull request merged**
