### PR TITLE
Initial support for GVH5101/5012 and enum GVH5072 dev type

### PR DESCRIPTION
**Pull request by zrhutto**
Apologies for the separate pull request - GitHub SNAFU. This is a revised commit based on #13

### CODE REVIEW

**Comment by zrhutto** [comment]
I’m a little wary of forcing users to specify their device type (e.g., GVH5101 v. 5102 v. 5075 v. 5072), given that we have the logic to distinguish the model and parse the advertisement packet appropriately (feels like an unnecessary extra step), but perhaps that’s an improvement to make with a future refactoring.

**Comment by tony-fav** [comment]
That change doesn't force them to specify that model, just gives them the option if they want their user_config to be very specific. It's exposing user options that have no real effect essentially.

**Comment by tony-fav** [comment]
What's up with changing the humidity calculation? By my memory, it was a requirement to do that kind of shift when dealing with negative temperature values. `output_map['Humidity'] = ((basenum - 0x800000) % 1000)/10.0`

An alternate could be to calculate humidity as `output_map['Humidity'] = ((basenum & 0x7FFFFF) % 1000)/10.0`

**Comment by tony-fav** [comment]
Last but probably not last, do you have an example you could add to the spoof_devices.be?

**Comment by zrhutto** [comment]
Good catch on the humidity calculation. Chalk that up to hastiness (and the fact that the sensor seemed to still be reporting sane values…).

Sample packet also added to spoof_devices.be. Let me know if anything else stands out.

**Comment by tony-fav** [comment]
Looks good! Thanks for the contribution!

**Pull request merged**
